spring.application.name=challenge-customers-api-local

server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/customers_local
spring.datasource.username=kata_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.environment.message=EJECUTANDO EN AMBIENTE DEV LOCAL