spring.application.name=challenge-customers-api

server.port=9090
server.address=0.0.0.0
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://db:5432/customers_prod
spring.datasource.username=user_kata
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

app.environment.message=EJECUTANDO EN AMBIENTE PROD