spring.application.name=challenge-customers-api-dev

server.port=8080
server.servlet.context-path=/api

sspring.datasource.url=jdbc:postgresql://db:5432/customers_dev
spring.datasource.username=kata_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

app.environment.message=EJECUTANDO EN AMBIENTE DEV