spring.application.name=challenge-customers-api

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/customers_prod
spring.datasource.username=kata_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver